### ISSUE TITLE
Bug: foute suggesties in zoekvenster om bestaand kind toevoegen aan voogd

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#10]
Bug: op voogd-fiche een bestaand kind opzoeken dmv zoekwaarde -> de suggesties worden niet gefilterd obv de zoekwaarde
Repliceer:
1. Maak of update voogd
2. Type een zoekwaarde
![image](https://user-images.githubusercontent.com/39667455/40584659-1335cbdc-61a5-11e8-954a-6c167faf39cc.png)
Resultaat: alle kinderen worden weergegeven = NOT OK

**Comment by FKint** [comment]
should be fixed now too

**Comment by rdemol01** [comment]
retest ok
