### ISSUE TITLE
invoice layout 'uitnodiging tot betaling'

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#124]
Kan de tekst 'uitnodiging tot betaling' op 1 lijn getoond worden?
![image](https://user-images.githubusercontent.com/39667455/170866891-b821ca27-a751-47f4-b2ac-394c38748e13.png)

**Comment by FKint** [comment]
Fixed by https://github.com/FKint/playground-admin-app/pull/125
