### ISSUE TITLE
Change: registratie GUI, verplaats inchecken/transactiegeschiedenis

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#15]
Change: verplaats knoppen 'inchecken' en 'transactiegeschiedenis'
AS IS: links onder, naast elkaar
TO BE: rechts boven, onder elkaar (de tarief/saldo knoppen staan dan onder de knoppen inchecken/transactiegeschiedenis)
Schets:
![image](https://user-images.githubusercontent.com/39667455/41230865-9521111e-6d81-11e8-9ff9-3b24b57f0906.png)

**Comment by FKint** [comment]
e439190f33154d357d35bc30a6462099e846b908

**Comment by rdemol01** [comment]
muy bien
