### ISSUE TITLE
Bug: transactiegeschiedenis bij nieuwe registraties

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#17]
1 Nieuwe voogd gemaakt (clean)
2 Reg: vink weekvinkje aan, alles wordt betaald
![image](https://user-images.githubusercontent.com/39667455/41247849-8974c2e2-6daf-11e8-9260-b5b70fad03fa.png)
2 Reg: vink weekje uit, alles wordt (terug)betaald
![image](https://user-images.githubusercontent.com/39667455/41247882-a439fdae-6daf-11e8-943a-2c6ff98b2847.png)
3 Reg: vink weekje aan, er wordt 0 euro betaald
![image](https://user-images.githubusercontent.com/39667455/41247921-bf5aaaac-6daf-11e8-8ded-17147bf5e0c6.png)
4 Transactiegeschiedenis
![image](https://user-images.githubusercontent.com/39667455/41248000-ef23d542-6daf-11e8-90a7-0ba419cb2439.png)
Dit moest eigenlijk zijn:
Tran1    Verwacht 22.50    Verschil 0.00
Tran2   (as is)
Tran3    Verwacht 22.50   Verschil -22.50

**Comment by FKint** [comment]
022c06de18e8c83bc7800afd46278dabe86e91c7

**Comment by rdemol01** [comment]
Calculatie is nu correct. Maar de labels 'Betaald' en 'Verwacht' staan fout. Die moeten gewisseld worden. Zie #19 
![image](https://user-images.githubusercontent.com/39667455/41376709-4cfd8a04-6f5a-11e8-8926-c10bf4de58ad.png)

**Comment by rdemol01** [comment]
Calculatie is correct. Issue resolved.
