### ISSUE TITLE
Change: checkbox 'factuur' op voogd

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#21]
Doel: minder manueel werk voor end user + minder kans op invoer fouten

Verwacht in productie: 25 juni

Assumptie: alle voogden op factuur worden standaard voor ALLE kosten gefactureerd. Er is geen uitsplitsing naar bepaalde kosten op factuur en bepaalde kosten contant te betalen.

**Change:**
Deel 1: voeg checkbox toe op voogd met label 'factuur'
![image](https://user-images.githubusercontent.com/39667455/41254136-da47d520-6dc2-11e8-88f9-65989c611ea5.png)
Deel 2: als de checkbox aangevinkt is voor deze voogd, dan blijft 'received money' value op 0 te staan, ook wanneer de user verschillende checkboxes (dag week ijs lijst) aan of uit zet. De user kan wel manueel de waarde 0 wijzigen naar een andere waarde.
![image](https://user-images.githubusercontent.com/39667455/41254188-0ec57b2c-6dc3-11e8-9ca6-14de71329fd9.png)

**Comment by rdemol01** [comment]
Update: we hebben een 'GO' voor deze functionaliteit :-) 
Geen must, maar wel meerwaarde om fouten en hertellen van de kassa te vermijden

**Comment by FKint** [comment]
Zal niet meer voor dit jaar zijn.

**Comment by rdemol01** [comment]
OK voor 2019

**Comment by FKint** [comment]
@rdemol01 Klaar voor verificatie

**Comment by rdemol01** [comment]
Kan nog niet testen zolang https://github.com/FKint/playground-admin-app/issues/27#issuecomment-493776576 open staat

**Comment by FKint** [comment]
update staat online

**Comment by rdemol01** [comment]
test OK
