### ISSUE TITLE
Change: transactiegeschiedenis, labels vertalen

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#22]
Dit mag worden:
Tarief
Verwachte bedrag
Ontvangen bedrag
Remarks
Vorig saldo
Nieuw saldo

![image](https://user-images.githubusercontent.com/39667455/41377436-4963e3be-6f5c-11e8-8103-ecad6ab74197.png)

**Comment by FKint** [comment]
596405d

**Comment by rdemol01** [comment]
'Ontvangen' mag toch 'Betaald' worden. Dan ligt dit ook in lijn met de labels in het scherm transactiegeschiedenis. #sorry

**Comment by FKint** [comment]
28e4a7cb7c93d9673ca46b98aa118858f2e2bfc5

**Comment by rdemol01** [comment]
OK!
