### ISSUE TITLE
Bug: kassa afsluiten breaks app

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#23]
When you sluit de kassa, the app goes BOOM
![image](https://user-images.githubusercontent.com/39667455/41378579-c0ce6d18-6f5f-11e8-9243-bc65c5f63b74.png)
Result: error page voor alle pagina's
![image](https://user-images.githubusercontent.com/39667455/41378600-d0235954-6f5f-11e8-9e9a-52c4d474a498.png)

**Comment by FKint** [comment]
0b6966c

**Comment by rdemol01** [comment]
retest ok
