### ISSUE TITLE
Opvang VM/AV als extraatje op scherm Registration

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#26]
Voeg 'extraatje' toe: "Opvang VM" en "Opvang AV"
Verwacht in productie: 25 juni
Het doel is:
- op scherm Registration tien nieuwe records krijgen
- de vinkjes voegen 0.50 euro toe aan het te betalen saldo (zoals al het geval is voor 'ijsjes')
- de vinkjes mogen enkel aangevinkt worden als het kind die dag/week al aanwezig staat (zoals al het geval is voor 'ijsjes')

Nieuwe records:
- Maandag Opvang VM
- Dinsdag Opvang VM
- xxx
- xxx
- xxx
- Maandag Opvang AV
- Dinsdag Opvang AV
- xxx
- xxx
- xxx
![image](https://user-images.githubusercontent.com/39667455/56869853-8f6acd00-6a06-11e9-9bcc-9badf802ec49.png)

**Comment by FKint** [comment]
Kun je laten weten of de functionaliteit goed genoeg is momenteel?

**Comment by rdemol01** [comment]
Must-haves zijn OK. 
De GUI laat ik nog beoordelen door end users.

**Comment by FKint** [comment]
ok. Je kunt dit opnieuw openen als er toch nog iets gedaan moet worden.
