### ISSUE TITLE
Factuur genereren

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#27]
Doel: factuur in PDF genereren per voogd per kind
Voordeel: we moeten facturen niet meer manueel maken
--> 10 uur minder werk per zomer 
--> minder kans op fouten

Verwacht in productie: 14 augustus

**Out of scope:**
- Vermeld enkel de totaalsom per kind. Het openstaande saldo mag niet vermeld worden. We gaan uit van de assumptie dat gezinnen steeds ofwel 1. volledig op factuur werken, ofwel 2. alles cash betalen tijdens de zomer. Dus het openstaande saldo zou altijd gelijk moeten zijn som van facturen alle kinderen in het gezin. Eventuele uitzonderingen moeten door jokkebrok administratief opgelost worden.

**Dependencies:**
- Op scherm Voogd moet er een nieuw tekstveldje 'Sociale instantie' komen. De waarde zal op de factuur geprint worden.
- Opvang 's ochtends en 's avonds moet ook gecapteerd kunnen worden door bureau medewerkers. Zie change https://github.com/FKint/playground-admin-app/issues/26

**Report spec:**
Parameters: child ID, family ID, year ID
1. Fixed text: 'Speelpleinwerking Jokkebrok vzw' + [variable street] + [variable town] + fixed text 'info@jok...'
2. FName en LName uit Child record
3. SocialContact uit Family record / 3. Year uit Year record
4. Family ID + hypen + Child ID
5. In geval van weektarief: vul 'van' en 'tot' in.
6. In geval van dagtarief: vul 'van' in.
7. Weektarief of dagtarief zoals het weergegeven wordt op scherm Registration. Rekening houden met: 2e kind, sociaal tarief. 
8. Eén kolom per type extraatje. Nu: ijsje, opvang VM, opvang AV.
9. Sum list.price where list.family&child = registration.family&child and list.date = registration.date
10. Niet weergeven. Out of scope.
11. Niet weergeven. Out of scope.
12. Totaal aankopen (dag, week, extraatjes, lijsten) (niet saldo)
12. Fixed text: Gelieve [insert value from 12.] euro over te schrijven op rekeningnummer [variable bankaccount] met referentie [year]-[family ID]-[child ID]-[child LName].
13. One line per list found in 9. Text: [list date] + [list description] + € + [list price]
![image](https://user-images.githubusercontent.com/39667455/56870270-584bea00-6a0d-11e9-8169-b745f3cf081a.png)
![image](https://user-images.githubusercontent.com/39667455/56870272-5f72f800-6a0d-11e9-9018-f5d2a4b2cc15.png)
Bron data
Year: 4
Family: 74
Child: 104
![image](https://user-images.githubusercontent.com/39667455/56870310-e6c06b80-6a0d-11e9-8674-d1abf2483315.png)

**Report file name:**
Voorbeeld: Uitnodiging tot betaling - 2019 43 53 Demol Roderick.pdf
Fixed: Uitnodiging tot betaling - 
Variable: Year + Family ID + Child ID + Child LName + FName

**Report trigger:**
Voeg een knop/link toe op scherm Voogd. Wanneer je hier op klikt, dan downloadt de browser een aparte PDF per kind van het gezin.

**Comment by FKint** [comment]
- Waar komen de lijsten met prijs? (onder overige?)
- Die variabele street, town etc. op welke manier zijn die variabel? Handmatig in te vullen elke keer een factuur gemaakt wordt? Constant voor een werkingsjaar?

**Comment by rdemol01** [comment]
- Lijsten: onder Overige
- Factuuradres: per jaar

**Comment by FKint** [comment]
En lijsten zonder datum?

**Comment by rdemol01** [comment]
Lijsten zonder datum:
- Niet in kolom overzicht tonen
- Wel onderaan tonen bij de toelichting
- Bedrag wel meenemen in totaal
- In de praktijk nog niet voorgevallen eigl

**Comment by FKint** [comment]
Klaar voor verificatie

**Comment by rdemol01** [comment]
Voogd: Social contact
Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
Reproduce steps:
-voogd: "wijzig"
-wijzig "social contact" naar nieuwe waarde
-klik "opslaan" en "sluiten"
-voogd: "wijzig"
Result: nieuwe waarde werd niet opgeslagen

**Comment by rdemol01** [comment]
Voogd: Needs Invoice
Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
Reproduce steps:
-voogd: "wijzig"
-wijzig "needs invoice" naar nieuwe waarde
-klik "opslaan" en "sluiten"
-voogd: "wijzig"
Result: nieuwe waarde werd niet opgeslagen

**Comment by rdemol01** [comment]
Genereer PDF Invoice
AS IS: file name bevat year id
Voorbeeld: Uitnodiging tot betaling - 6 367 576 Demol Roderick.pdf
TO BE: file name bevat year name
Voorbeeld: Uitnodiging tot betaling - _**2019**_ 367 576 Demol Roderick.pdf

**Comment by rdemol01** [comment]
Genereer PDF Invoice
-Logo staat op invoice in year 2019 (test en prod) = OK
-Logo staat er niet op in year 2018 (test en prod) = NOK

**Comment by FKint** [comment]
> Genereer PDF Invoice
> -Logo staat op invoice in year 2019 (test en prod) = OK
> -Logo staat er niet op in year 2018 (test en prod) = NOK

Non-issue. Invoice informatie (inclusief image) is per jaar, zoals gevraagd [eerder](https://github.com/FKint/playground-admin-app/issues/27#issuecomment-491517047) in deze thread.

**Comment by rdemol01** [comment]
> > Genereer PDF Invoice
> > -Logo staat op invoice in year 2019 (test en prod) = OK
> > -Logo staat er niet op in year 2018 (test en prod) = NOK
> 
> Non-issue. Invoice informatie (inclusief image) is per jaar, zoals gevraagd [eerder](https://github.com/FKint/playground-admin-app/issues/27#issuecomment-491517047) in deze thread.

Adres is inderdaad per jaar. 
Logo mag fixed zijn, zodat dat niet elk jaar moet opgezet worden.

**Comment by rdemol01** [comment]
Geen bijkomende opmerkingen momenteel.

**Comment by FKint** [comment]
Zal logo toch laten as-is. Aanmaken van een nieuw jaar gebeurt met een clone-command dat alles overneemt dus is geen extra moeite.

**Comment by rdemol01** [comment]
> Zal logo toch laten as-is. Aanmaken van een nieuw jaar gebeurt met een clone-command dat alles overneemt dus is geen extra moeite.

Aha. Prima dan

**Comment by rdemol01** [comment]
> Voogd: Social contact
> Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
> Reproduce steps:
> -voogd: "wijzig"
> -wijzig "social contact" naar nieuwe waarde
> -klik "opslaan" en "sluiten"
> -voogd: "wijzig"
> Result: nieuwe waarde werd niet opgeslagen

looks OK now

**Comment by rdemol01** [comment]
> Voogd: Needs Invoice
> Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
> Reproduce steps:
> -voogd: "wijzig"
> -wijzig "needs invoice" naar nieuwe waarde
> -klik "opslaan" en "sluiten"
> -voogd: "wijzig"
> Result: nieuwe waarde werd niet opgeslagen

retest still NOK

**Comment by FKint** [comment]
update staat online

**Comment by rdemol01** [comment]
> > Voogd: Needs Invoice
> > Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
> > Reproduce steps:
> > -voogd: "wijzig"
> > -wijzig "needs invoice" naar nieuwe waarde
> > -klik "opslaan" en "sluiten"
> > -voogd: "wijzig"
> > Result: nieuwe waarde werd niet opgeslagen
> 
> retest still NOK

OK: needs_invoice op TRUE zetten en opslaan
NOK: needs_invoice op FALSE zetten en opslaan -> blijft op TRUE staan

**Comment by rdemol01** [comment]
> > > Voogd: Needs Invoice
> > > Issue: inhoud veld kan niet gewijzigd worden na creatie / initiele waarde
> > > Reproduce steps:
> > > -voogd: "wijzig"
> > > -wijzig "needs invoice" naar nieuwe waarde
> > > -klik "opslaan" en "sluiten"
> > > -voogd: "wijzig"
> > > Result: nieuwe waarde werd niet opgeslagen
> > 
> > 
> > retest still NOK
> 
> OK: needs_invoice op TRUE zetten en opslaan
> NOK: needs_invoice op FALSE zetten en opslaan -> blijft op TRUE staan

retest OK

**Comment by rdemol01** [comment]
> Genereer PDF Invoice
> AS IS: file name bevat year id
> Voorbeeld: Uitnodiging tot betaling - 6 367 576 Demol Roderick.pdf
> TO BE: file name bevat year name
> Voorbeeld: Uitnodiging tot betaling - _**2019**_ 367 576 Demol Roderick.pdf

retest OK

**Comment by rdemol01** [comment]
all ok

**Comment by FKint** [comment]
update staat online

**Comment by rdemol01** [comment]
retest ok
