### ISSUE TITLE
Create registration: check for existing registration on other guardians

### ISSUE THREAD

**Issue by RDEMOL** [FKint/playground-admin-app#3]
At a specific moment in time a child can be registered for up to one specific day across all guardians. When user attempts to create registration for a second guardian for the same child on the same day, the user should be warned.
**Reproduce**
Step 1
![image](https://cloud.githubusercontent.com/assets/1383142/25567155/01ac5148-2de8-11e7-825a-0ae62b1b8518.png)
Step 2
![image](https://cloud.githubusercontent.com/assets/1383142/25567157/11709e0e-2de8-11e7-99e9-33564b8b9d24.png)
**Result:** 
-new registrations for guardian 'Bertrand' have not been saved
-user was not warned about existing registrations on other guardians
-application returns error in the background (this is not visible for end user)
![image](https://cloud.githubusercontent.com/assets/1383142/25567233/c9d8a846-2de9-11e7-8ef6-885fe715442d.png)
**Desired result:**
-user is warned about existing registrations on other guardians
-registration page remains unchanged, available for the user to correct or cancel

**Comment by rdemol01** [comment]
Works OK. No errors.
Accepted risk:
- You can subscribe a child id multiple times on the same day for different family id's. The attendance list will show the child twice. Backoffice has to identify and fix it when this happens.

**Comment by rdemol01** [comment]
@FKint please close
