### ISSUE TITLE
Setup 2019

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#38]
Gaarne de opzet doen voor 2019,

Test env koppelen aan user adm..
Prod env koppelen aan user inf..

Setup test/prod:

Dagen:
- 1 juli 2019 tot en met 14 aug 2019
- enkel weekdagen

Werkingen
Afkorting	Naam	Startjaar	Eindjaar
12+ | Tieners | 2005-01-01 | 2007-01-01
6-12 | Grote | 2007-01-01 | 2014-01-01
KLS | Kleuters | 2014-01-01 | 2017-01-01

Extraatjes
Omschrijving	Prijs	Volgorde
IJsje	0.50	1
Opvang VM 0.50	2
Opvang AV 0.50	3

Dagdelen
Omschrijving	Volgorde
Lunch	1
Thuis	2

Tariefplannen
Omschrijving	Afkorting	Dagprijs eerste kind	Dagprijs latere kinderen	Weekprijs eerste kind	Weekprijs latere kinderen
Normaal	NRML	5.00	4.00	22.50	18.50
Sociaal	SCL	2.50	2.00	12.00	9.50

Invoice setup
Speelpleinwerking 
Jokkebrok vzw
Ter Zwaanhoek 79
8400 Oostende
info@jokkebrok.be

**Comment by FKint** [comment]
@rdemol01 Klaar voor verificatie.

**Comment by rdemol01** [comment]
Kun je de invoice address wijzigen in TEST 2018 ?
-Ter Zwaanhoek 79 wordt Nukkerwijk 64
-8400 Oostende wordt 8450 Bredene

**Comment by rdemol01** [comment]
Geen bijkomende opmerkingen momenteel.

**Comment by rdemol01** [comment]
> Kun je de invoice address wijzigen in TEST 2018 ?
> -Ter Zwaanhoek 79 wordt Nukkerwijk 64
> -8400 Oostende wordt 8450 Bredene

is OK, thx
