### ISSUE TITLE
bug: link existing child 'fails' during family creation

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#46]
Issue: browser toont foutmelding wanneer je een bestaand kind wil linken tijdens het creëeren van een nieuwe voogd
Reproduce:
-"nieuwe voogd toevoegen"
-klik "voogd aanmaken"
-zoek een naam op in "bestaand kind toevoegen"
Result:
-browser melding "Adding child failed!"
-console: Failed to load resource: the server responded with a status of 500 (Internal Server Error)
-als je de nieuwe voogd dan opzoekt, dan zie je dat het kind dan toch gelinkt is. De melding is een valse negatief en hoeft eigenlijk niet getoond te worden.

**Comment by FKint** [comment]
update staat online

**Comment by rdemol01** [comment]
retest OK
