### ISSUE TITLE
bug: updating list 'show on form' sets date to blank

### ISSUE THREAD

**Issue by rdemol01** [FKint/playground-admin-app#47]
Issue: wanneer je de 'show on att... form' van een lijst wijzigt, dan zet het de date op blank
Reproduce:
-"nieuwe lijst maken"
-vul naam en date in
-zet "show on attendance form" to TRUE
-klik "opslaan"
-wijzig "show on attendance form" to FALSE
-klik "opslaan"
Result:
-date werd blank gemaakt

**Comment by FKint** [comment]
update staat online

**Comment by rdemol01** [comment]
retest OK
